name: Dev deployment
on:
    pull_request:
        branches:
            main
    push:
        branches:
            main
    workflow_dispatch:

jobs:
    glue_dev_deploy:
        uses: ./.github/workflows/deployment_template.yaml
        with:
            environment: dev
            step_name: apply
        secrets:
            git_role: ${{ secrets.IAM_ROLE }}