
name: Destroy resources
on:
    workflow_dispatch:
        inputs:
            environment:
                type: choice
                required: true
                options: ["dev","test","prod"]
                description: Select the AWS environment to destroy resources in
jobs:
    destroy:
        uses: ./.github/workflows/deployment_template.yaml
        with:
            step_name: destroy
        secrets:
            git_role: ${{ secrets.IAM_ROLE }}